[package]
name = "mqtt-ha"
version = "0.1.0"
edition = "2021"

[dependencies]
mqtt-async-client = "0.3"
tokio = { version = "1.2", features = ["macros", "time"] }
env_logger = "0.11"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
